"""Initial schema

Revision ID: 3c5059432bb2
Revises: 
Create Date: 2026-02-22 17:43:46.455996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5059432bb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connectors_id'), ['id'], unique=False)

    op.create_table('mapping_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source_connector_id', sa.Integer(), nullable=True),
    sa.Column('target_connector_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['target_connector_id'], ['connectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mapping_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapping_documents_id'), ['id'], unique=False)

    op.create_table('field_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_document_id', sa.Integer(), nullable=False),
    sa.Column('source_table', sa.String(length=255), nullable=False),
    sa.Column('source_column', sa.String(length=255), nullable=False),
    sa.Column('target_table', sa.String(length=255), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('transformation', sa.String(length=500), nullable=True),
    sa.Column('source_sql_expr', sa.Text(), nullable=True),
    sa.Column('target_sql_expr', sa.Text(), nullable=True),
    sa.Column('dq_rule', sa.String(length=255), nullable=True),
    sa.Column('test_notes', sa.Text(), nullable=True),
    sa.Column('is_key', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mapping_document_id'], ['mapping_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_mappings_id'), ['id'], unique=False)

    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('passed_cases', sa.Integer(), nullable=True),
    sa.Column('failed_cases', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mapping_document_id'], ['mapping_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_runs_id'), ['id'], unique=False)

    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_document_id', sa.Integer(), nullable=False),
    sa.Column('field_mapping_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('source_sql', sa.Text(), nullable=True),
    sa.Column('target_sql', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_mapping_id'], ['field_mappings.id'], ),
    sa.ForeignKeyConstraint(['mapping_document_id'], ['mapping_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_id'), ['id'], unique=False)

    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_run_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('source_value', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('mismatch_count', sa.Integer(), nullable=True),
    sa.Column('mismatch_sample', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_results_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_id'))

    op.drop_table('test_results')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_id'))

    op.drop_table('test_cases')
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_runs_id'))

    op.drop_table('test_runs')
    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_mappings_id'))

    op.drop_table('field_mappings')
    with op.batch_alter_table('mapping_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapping_documents_id'))

    op.drop_table('mapping_documents')
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connectors_id'))

    op.drop_table('connectors')
    # ### end Alembic commands ###
